### ISSUE TITLE
TinyMCE causes Text on Cards to become HTML code

### ISSUE THREAD

**Issue by danie1zhang** [tl-its-umich-edu/canvas-app-explorer#105]
![image](https://user-images.githubusercontent.com/27447/144320653-410ce88e-db36-41e8-9eb0-f1f3549cd302.png)

**Comment by jonespm** [comment]
Looks like this might be relevant.
https://stackoverflow.com/questions/27934238/rendering-raw-html-with-reactjs

Seems like you have to `dangerouslySetInnerHTML` to get it to render raw HTML. Looking into replacing the code with this since this is all from a trusted source.
