### ISSUE TITLE
Large spacing between Description and Privacy Agreement on Learn More Card

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/canvas-app-explorer#109]
On the Learn More side of the card, there's a large gap between Description and Privacy Agreement. Even changing the height of this card doesn't change anything. It seems like any extra whitespace should go at the bottom.

It might be that this description height is hard coded in Plasmic. Need to look into this to better format the boxes.

![image](https://user-images.githubusercontent.com/27447/144320788-87971e34-8447-4979-9e03-2767d94e15eb.png)

**Comment by danie1zhang** [comment]
Resolved, product card design was changed
