### ISSUE TITLE
Button placement inconsistency on main card

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/canvas-app-explorer#127]
The alignment of the buttons on the main cards seem to be slightly out of line for some reason. These should all be in the same horizontal position.

<img width="787" alt="image" src="https://user-images.githubusercontent.com/27447/156186554-e9fb2799-8653-4fcc-b2c2-f5e4fb80d4c0.png">

**Comment by ssciolla** [comment]
This should have been resolved by #158.
