### ISSUE TITLE
Disable old admin backend and trust LTI for users that are admin

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/canvas-app-explorer#147]
We currently have a backend login for admin that we're using in the LTI version. When in LTI this should be disabled and there should be some link displayed for users who are super users in the database to be able to click on and access the admin interface. 

This link may need to be added to plasmic or maybe we can just put it in the corner. We currently don't have any menus in this app but maybe it could use a ☰ left of the "Canvas App Explorer" title and admin could be in there. Not sure what else though?

**Comment by jonespm** [comment]
The link part was implemented on #207

**Comment by jonespm** [comment]
I updated the [Wiki](https://github.com/tl-its-umich-edu/canvas-app-explorer/wiki/Configuring-LTI-1.3) with the new instructions for this.

**Comment by zqian** [comment]
I verified in an incognito window,  went to `https://test-cae.tl.it.umich.edu/admin/`, I got redirected to `https://test-cae.tl.it.umich.edu/admin/login/?next=/admin/` with Server Error (500), and log message `[log.py:224] Internal Server Error: /admin/login/`

On the other hand, via LTI launch of CAE tool, and if I am marked as admin in Django (is_super_user), I can use the "ADMIN" link on the top right corner to go to the Admin UI.
