### ISSUE TITLE
Provide a Django Admin screen for deleting from canvas_oauth_canvasoauth2token

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/canvas-app-explorer#175]
If someone's token doesn't work for some reason the only way to fix it is to clear it out of the database manually. It would be nice if an admin could clear out a single or all of the tokens to reset the app though the UI in the canvas_oauth_canvasoauth2token.

It shouldn't show the actual tokens, just the user and the expiration time and give an option to remove. 

This might be semi-related to implementing #120 but can be independent. Though we might have to have a separate package for this or contribute the fix to the upstream repository. (Or a fork of it)

**Comment by ssciolla** [comment]
@jonespm, I think this already exists, though maybe we want to customize it a bit more.

<img width="324" alt="Screen Shot 2022-05-25 at 5 44 13 PM" src="https://user-images.githubusercontent.com/35741256/170372555-52050978-429a-47b0-8b9a-34b4ee1ca24c.png">

**Comment by jonespm** [comment]
Wow, okay, I guess I never noticed that! Thanks! Maybe we could look into something to style up the admin page a little to help direct admins to where they need to go with like https://github.com/django-admin-tools/django-admin-tools

Or write something else in the future. I just didn't know about this. Can close it.
