### ISSUE TITLE
Don't consider HTML formatting in character count limits

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/canvas-app-explorer#179]
If someone includes a link or something like that in the short description (or other fields that have character limits) it's including that as part of the character count and preventing it from saving. It should have a way to consider the max_length without any formatting characters. 

I think we'll have to use a custom max_length validator https://docs.djangoproject.com/en/4.0/ref/validators/

And maybe run this through https://docs.djangoproject.com/en/4.0/ref/utils/#django.utils.html.strip_tags.

**Comment by ssciolla** [comment]
There's a migration that needs to be generated from this change.

**Comment by zqian** [comment]
@ssciolla why we need a migration for this?

**Comment by ssciolla** [comment]
It's just how Django works; migrations track model changes, and adding a validator is a model change, even if it doesn't affect the database. It's not a critical problem, though there may be reasons why it matters that I'm not thinking of. It just seems like a good thing to do housekeeping wise.

**Comment by zqian** [comment]
OK. How about creating a new issue to add the migration file, and close this one?

**Comment by zqian** [comment]
Close this issue and track the migration file in #256
