### ISSUE TITLE
MySQL 5.7 problem with MacBook M1

### ISSUE THREAD

**Issue by zqian** [tl-its-umich-edu/canvas-app-explorer#186]
Docker-compose up throws the following error with MySQL 5.7 on MacBook M1
```
➜  canvas-app-explorer_copy git:(main) ✗ docker-compose up
WARNING: The TZ variable is not set. Defaulting to a blank string.
Creating network "canvas-app-explorer_copy_default" with the default driver
Pulling mysql (mysql:5.7)...
5.7: Pulling from library/mysql
ERROR: no matching manifest for linux/arm64/v8 in the manifest list entries
```

We've upgrade the dev MySQL server to MySQL v8.0.27, so it makes sense to update the docker-compose file to use MySQL 8

**Comment by jonespm** [comment]
After switching to MySQL 8 my local startup is taking nearly 3 minutes on a empty database. Adding the 2 options to the command in docker-compose.yml pushes it down to like 1 second.  Probably will have to put these in but I'm not sure if there's any downsides.

Saw this mentioned on https://stackoverflow.com/a/42221456/3708872

`'--skip-name-resolve', '--skip-external-locking'`
