### ISSUE TITLE
OAuth to allow usage of Canvas API

### ISSUE THREAD

**Issue by danie1zhang** [tl-its-umich-edu/canvas-app-explorer#2]

**Comment by jonespm** [comment]
Here's my idea
- [x] Implement or use an existing OAuth library 
- [ ] If user is instructor via LTI launch, get the status of tools placed in their site. This will initiate an OAuth request
This will probably be via the [visible_course_nav_tools](https://canvas.instructure.com/doc/api/external_tools.html#method.external_tools.visible_course_nav_tools) api or the [tabs API](https://canvas.instructure.com/doc/api/tabs.html). It doesn't looks like these are fully implemented in CanvasAPI Python
- [ ] Show the appropriate add/remove buttons. When the user clicks this button use the OAuth to add/remove this tool and switch the button.
