### ISSUE TITLE
Pass Canvas error information to the Django API error response

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/canvas-app-explorer#205]
I think this PUT call invokes the LTIToolViewSet>update function inside Views.py. In line 57 of Views.py, where the Response is returned in Exception handling block:

```
try:
	manager.update_tool_navigation(canvas_id_num, not navigation_enabled)
except Exception as err:
	logger.error(err)
	return Response(status=500)
```

Could the Response object also include the err message, or some other user friendly error message?

_Originally posted by @zqian in https://github.com/tl-its-umich-edu/canvas-app-explorer/pull/196#discussion_r898655295_

**Comment by zqian** [comment]
Ran the test.py file and verified the successful run of test cases.
