### ISSUE TITLE
If refresh token is invalid, rather than returning invalid_grant, just remove token and retry

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/canvas-app-explorer#208]
I believe that when calling this [get_oauth_token](https://github.com/tl-its-umich-edu/canvas-app-explorer/blob/7c877a5c8fb5388481556ef86b3330ec2c068dd2/backend/views.py#L7) code if the access token is invalid it ends up printing
`Error: refresh_token request failed to get a token: Error: invalid_grant`

We'd ideally want it to try to remove this users token and try the process again. It's possible that something changed that caused the token to become invalid and clearing it automatically would fix it. 

I'm not 100% sure where the error is pushed up from but we'd have to investigate a little and hopefully can take care if it in our code rather than the library.

To reproduce
* Launch the app and get a token.
* Go into the Admin interface and click on Canvas Oauth2 Tokens
* Click on the token for your user id
* Change the refresh token and update the date to be "now" so it invalidates it
* Try to launch again. You should get this error.

Expectation is that it does one refresh to try to clear out and retry rather than just fail.

We may also want to test the case if the user removes their token from Canvas, it should be able to handle this. 

This workaround is currently referenced at the [bottom of the wiki](https://github.com/tl-its-umich-edu/canvas-app-explorer/wiki/Configuring-LTI-1.3) with a manual workaround.

**Comment by zqian** [comment]
I think this error after the Canvas test instance reset, it invalidate the old Canvas OAuth2 token?

**Comment by jonespm** [comment]
Yes, this will also happen after every Canvas test refresh. I'm not sure if there's other cases it could happen. We haven't tested many exception cases for OAuth.

**Comment by roujiawang** [comment]
Performed tests according to the TEST PLAN
No unexpected behavior found.
