### ISSUE TITLE
Add configurable help link to the navigation bar

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/canvas-app-explorer#210]
We will need a way to link from the application to the result of #37. Adding a link to the navigation bar (either as a separate link button or as part of a menu) would be a logical solution and something we have done in other projects.

**Comment by ziegler1960** [comment]
Tested on https://canvas-test.it.umich.edu/courses/587202/
Verified Help link is displayed at the far right position inside the CAE tool banner
Verified that link opens a new browser tab to the CAE project repository in GitHub
