### ISSUE TITLE
Replace X_FRAME_OPTIONS with CSP

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/canvas-app-explorer#220]
X_FRAME_OPTIONS was only intended to be used as a quick temporary test. We should [replace that with CSP similar to MyLA.](https://github.com/jonespm/student-dashboard-django/commit/69917e4580be040aaea3a7e3b372176dd86827d3)

https://github.com/tl-its-umich-edu/canvas-app-explorer/blob/210fe85bc49e0e8a8e7051430931b650fa1111d8/backend/settings.py#L151

**Comment by zqian** [comment]
verified LTI integration works in Canvas test instance after the following setting is enabled in .env file:

CSP_FRAME_ANCESTORS=canvas-test.it.umich.edu
