### ISSUE TITLE
Update text, increase visibility of refresh alert when tools are updated

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/canvas-app-explorer#224]
Per feedback from the UX team, we need to update the text of the refresh alert to be "Refresh the page to update the tool's appearance in the left-hand navigation." Ideally, we also need to do something to make the alert more noticeable (probably through a snackbar/toast) if the user has scrolled down to where the top of the page isn't visible.

**Comment by ziegler1960** [comment]
tested on https://canvas-test.it.umich.edu/courses/587202/
Verified that the refresh message displays, message is dismissible, message does not re-display after adding back the tool, but does display after browser refresh and adding/removing more tools
