### ISSUE TITLE
IDs of 'add-tool-button' and 'remove-tool-button' were flagged by a11y check for not being unique.

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/canvas-app-explorer#226]
The issue that the[ aXe checker](https://chrome.google.com/webstore/detail/axe-devtools-web-accessib/lhdoppojpmngadmnindnejefpokejbdd) flagged was` ‘Ensures every id attribute value of active elements is unique’ because these buttons have a hardcoded id. Perhaps we could just pass in and append the id of the tool cards. Unless there's some better recommendation for unique ids in React. 

https://github.com/tl-its-umich-edu/canvas-app-explorer/blob/de65c5c7eb76903fe535ea9befd54229c96af060/frontend/app/components/toolButtons.tsx#L9

**Comment by ssciolla** [comment]
Yeah, I was too cavalier with the IDs. I will make them unique.

**Comment by zqian** [comment]
verified this issue is no longer flagged by Axe DevTools.
