### ISSUE TITLE
Add indicator that tool is already available in the course

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/canvas-app-explorer#230]
During usability testing, some users were confused initially by the "Remove tool" button, not realizing the tool was already available. We could add some kind of indicator -- a badge, icon, etc. -- that communicates the tool is already available, installed, etc.

**Comment by zqian** [comment]
reopen for QA testing

**Comment by roujiawang** [comment]
Performed tests per TEST PLAN on the Canvas App Explorer Test site.
No unexpected behavior found.
