### ISSUE TITLE
Database images aren't cached, add cache control

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/canvas-app-explorer#241]
I noticed that images that are loaded from the database aren't cached. This is going to put unnecessary load and extra traffic on us with every request

![image](https://user-images.githubusercontent.com/27447/178051339-96d96e85-6b06-450c-abb8-97bcb0000692.png)

I [found this thread](https://github.com/victor-o-silva/db_file_storage/issues/103) here about how we can pass headers along to this url.

To test if this working, after the first reload all the images in the network tab should be coming from disk cache.

![image](https://user-images.githubusercontent.com/27447/178052330-506aea8d-02d9-4afd-b98a-bdec72644e2d.png)

If a new image is uploaded the name is changed, so I think this caching for this [default recommended year is fine. ](https://medium.com/pixelpoint/best-practices-for-cache-control-settings-for-your-website-ff262b38c5a2)

**Comment by ssciolla** [comment]
I can QA this.

**Comment by zqian** [comment]
verified the LTI logo images are cached.
