### ISSUE TITLE
Do pre-release dependency review and update

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/canvas-app-explorer#252]
Prior to the initial release, it makes sense to check dependency versions for Python and Node packages and pick up patch or minor versions if no modifications to source code are needed.

**Comment by zqian** [comment]
Test successfully with the [PRT test plan](https://docs.google.com/spreadsheets/d/1SSwXBbatRyXCFG76kGnjZoQd7zlVr7KgYQdDuE3F44k/edit#gid=0).
