### ISSUE TITLE
Add `django-watchman` status check endpoint

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/canvas-app-explorer#258]
Not sure if this is 100 percent required for the initial release, but it is something we use in our other Django applications. https://github.com/mwarkentin/django-watchman

**Comment by ziegler1960** [comment]
Test Plan:
navigate to this URL (https://test-cae.tl.it.umich.edu/watchman/) and ensure that it sends back OK data about the database and cache.

In Chrome Version 103.0.5060.134 (Official Build) (x86_64), navigated to the provided test URL.  Response:
{"databases": [{"default": {"ok": true}}], "caches": [{"default": {"ok": true}}]}

Passed.
