### ISSUE TITLE
Change `watchman` URL mount point to `status`, fix logging

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/canvas-app-explorer#263]
To keep consistent with other applications, we should mount the `watchman` application URLs at `status` instead of `watchman`. We may also want to add a `bare_status` endpoint.

We should also change the log level in the logger so it only logs messages with level `INFO` or `WARNING` or higher. It could be configurable also.

**Comment by zqian** [comment]
Tested on the CAE test server, the /status endpoint is in place; /watchman endpoint is removed; log level is set to INFO.
