### ISSUE TITLE
Card TinyMCE text fields: paragraphs separated by spaces instead of line breaks

### ISSUE THREAD

**Issue by roujiawang** [tl-its-umich-edu/canvas-app-explorer#274]
**Expected behavior**

Multiple paragraphs entered into the TinyMCE fields in the backend should be formatted properly as separate paragraphs in the frontend.

**Current behavior**

Multiple paragraphs are smashed together and only separated by a couple of spaces. 
This is likely due to CSS settings in the frontend.

**Steps to recreate the problem**

In the admin view, in any empty textbox of any cards, do
1.  type "Hello"
2.  hit Enter
3. type "World"

Expected output:
>`Hello`
>`World`

Actual output:
> `Hello World`

**Comment by roujiawang** [comment]
Created [a pull request](https://github.com/tl-its-umich-edu/canvas-app-explorer/pull/275) to fix this issue.

**Comment by ziegler1960** [comment]
This fix has been verified - the test paragraphs entered on the backend are correctly formatted when viewing the card in the CAE frontend.

Test Course: https://umich.beta.instructure.com/courses/587202/external_tools/48681

- [ ] From the CAE tool on the test course, click Admin link at the upper right  to access the Admin UI
- [ ] Select 'Lti tools' to see the list of cards
- [ ] Click on a tool: Adobe Creative Cloud
- [ ] Delete the current content of the Short Description field ("Access Creative Cloud Express projects and apps within Canvas, and use them to create and complete their assignments.")
- [ ] In the Short Description field, type "Hello" -> hit Enter - > type "World". 
- [ ] Toggle the HTML editor button on the toolbar to verify <p> tags for each word 
- [ ] Click Save - LTI tool list loads
- [ ] Click View Site link to return to the CAE tool on the course
- [ ] Verify that "Hello" and "World" display as separate paragraphs, one word above the other with a line break separating the paragraphs
- [ ] Return to Admin UI -> Lti tools ->  click on the ACC listing
- [ ] Enter the original text into the Short Description field and click Save
- [ ] Return to the course and verify that the ACC edit has been saved with the original text
