### ISSUE TITLE
LTI Integration with Canvas and Openshift

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/canvas-app-explorer#36]
This is an epic from Zenhub

The issues related are
#14 
#2
#3
#49 
#84
#40 
#87 
#1 
#80

**Comment by ssciolla** [comment]
@jonespm, I think we're good here, right?

**Comment by jonespm** [comment]
Yes, this was originally an Epic managed by Zenhub and it looks like all issues are closed.
