### ISSUE TITLE
Switch project to using MySQL in dev instead of SQLLite

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/canvas-app-explorer#41]
Will need to switch the Docker Compose and the Django settings.

Example where we are doing this: https://github.com/tl-its-umich-edu/my-learning-analytics/blob/master/docker-compose.yml

**Comment by ssciolla** [comment]
So here would be the steps for making this happen (in a bit more detail), based on the current status of the project:

1) Add a `mysql` service to `docker-compose`.
  This is a standard pattern we use in our projects. MyLA example above is good, but also you can look at these:
  - Placement Exams (Python/Django, but no frontend): https://github.com/tl-its-umich-edu/placement-exams/blob/803fd0b41eecdc7034c0308fc420c813563ddb7e/docker-compose.yml#L4-L21
  - Canvas Course Manager (NodeJS/Express/Next, but uses the same MySQL patterns): https://github.com/tl-its-umich-edu/canvas-course-manager-next/blob/c39ecc85a96b5102a5885f8664d0af410324d448/docker-compose.yml#L29-L44
  
  Documentation for this is here: https://hub.docker.com/_/mysql
  
2) Add a configuration approach
  The application won't be too heavy on configuration, but it needs a solid approach for this and doesn't yet have it. To start with, you could use environment variables, added to the container environment using `environment` or `.env
