### ISSUE TITLE
Admin page isn't able to load static css files

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/canvas-app-explorer#50]
When logging into http://localhost:5000/admin/ the css isn't working and it's not able to get some files from static. This is probably either because these aren't being collected or the path isn't exposed correctly. Will look into fixing this. 

![image](https://user-images.githubusercontent.com/27447/122580324-d4597f80-d023-11eb-89ad-9851bc174433.png)

**Comment by ssciolla** [comment]
Looks like adding the `'django.contrib.staticfiles'` to the `INSTALLED_APPS` array in `settings.py` is the fix. https://docs.djangoproject.com/en/3.2/howto/deployment/wsgi/modwsgi/#serving-the-admin-files

**Comment by jonespm** [comment]
Hmm, it looks like when I add that it does fix the problem for the backend (admin page) but breaks some image links in the frontend. I think this was because I was trying to serve files from the frontend on the /static/ path and this takes over that path. I'll either have to get a more specific directory (like /static/plasmic) or get this path/directory to be served up by this staticfiles app.

**Comment by jonespm** [comment]
This **might** be resolved by also running the management command collectstatic, which should put the static files for the frontend into /static. But I felt like there might be an easier way of dealing with this since they are already collected by the frontend. 

I'll read more about this and how webpack-loader is doing this.
