### ISSUE TITLE
Add some migration file to pre-populate the tables with known values

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/canvas-app-explorer#54]
It would be nice if we pre-populated the stables like CanvasPlacement to have a few of the known defined placements. We also should pre-populate any other tables.

**Comment by ssciolla** [comment]
So, probably use a data migration to add the available Canvas Placements.

**Comment by jonespm** [comment]
I believe the idea is we'd sync the placements for each tool from Canvas via API eventually. This is not going to happen in the short term, so we're hardcoding them for now. I think we have it as a table so it can be dynamic and not require code changes if these placements ever change.

**Comment by ssciolla** [comment]
@jonespm, how about something like this? If it looks okay, I will open a PR after #134 is merged.
